### ISSUE TITLE
Repeating with `.` is not quite right

### ISSUE THREAD

**Issue by joeytwiddle** [dahu/vim-fanfingtastic#13]
Loving fanfingtastic, but...

If I do `d2f"` to delete everything up to (and including) the second `"` that works fine.

Now if I go to the next line and press `.` to repeat that action, it only sort-of works.

What it seems to do is delete the same number of chars as it did on the first run.

What it _should_ do is search for the second `"` and delete up to it.

Of course, this issue is only noticeable if the second `"` appears at a different column on the subsequent lines.  So quite often we don't notice this bug.

Would it be difficult to fix that?  (I accept that getting it to work with `.` at all is already impressive!)

**Comment by Lamby777** [comment]
I have `repeat.vim` and it still isn't working properly...

Edit: On a second try after reopening the editor, it seems to work...?!! I have no idea what could be causing it, but before I posted this it would type some `:` command without pressing enter whenever I pressed `.` to repeat a deletion that had `t` in it.
