### ISSUE TITLE
Repeat for change command no longer works

### ISSUE THREAD

**Issue by lervag** [dahu/vim-fanfingtastic#18]
When using the change command `c` with fanfingtastic the repeat command stops working. Example, consider following file:
```txt
Test
Testing
```
On first letter in file, do `ctsFa<esc>` to change the word to "Fast". Then go to next line and repeat with `.`, which gives the following result for me:
```txt
Fast
aesting
```

The above example was run with the minimal vimrc:
```vimL
set nocompatible

let &rtp = '~/.vim/bundle/vim-fanfingtastic,' . &rtp

filetype plugin indent on
syntax enable
```

I use vim version 7.4.537 on Arch Linux.

**Comment by dahu** [comment]
The repeat feature depends on tpope's [vim-repeat](https://github.com/tpope/vim-repeat).
I have successfully tested with vim 7.4.430

**Comment by lervag** [comment]
Yes, of course. My mistake!
