### ISSUE TITLE
f/F do not work properly in visual line mode

### ISSUE THREAD

**Issue by misterbuckley** [dahu/vim-fanfingtastic#21]
In visual line mode:

If you have a single line selected,
- `f` will go to the first match it can find, unless there is a match on the current line, in which case it always goes to the match closest to the beginning of the line, regardless of cursor position
- `F` always goes to the last occurrence in the lines above the current, ignoring matches on the current line

If you have multiple lines selected and the line you have selected is the top line of your selection,
- `f` will go to the first match it can find, unless there is a match on the current line, in which case it always goes to the match closest to the beginning of the line, regardless of current cursor position
- `F` always goes to the last occurrence in the lines above the current, ignoring matches on the current line

If you have multiple lines selected and the line you have selected is the bottom line of your selection,
- `f` always goes to the first occurrence in the lines below the current, ignoring matches on the current line
- `F` will go to the first match it can find, unless there is a match in the current line, in which case it always goes to the match closest to the end of the line, regardless of cursor position

**Comment by dahu** [comment]
Thank you for the report. I'll look into it tomorrow.

**Comment by dahu** [comment]
I found some time before bed. Good luck.

**Comment by misterbuckley** [comment]
Looks like that fixed it, thanks!

**Comment by dahu** [comment]
Great. You're welcome. Fixed #21.
